/*
 * This source file was generated by the Gradle 'init' task
 */
package it.unicam.cs.mpgc.rpg130901;

class MessageUtils {
    public static String getMessage() {
        return "Hello      World!";
    }
}
